apiVersion: v1
kind: Service
metadata:
  name: heliocentric-model-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32223
  selector:
    app: heliocentric-model
  type: NodePort
