apiVersion: v1
kind: Service
metadata:
  name: geocentric-model-svc
spec:
  ports:
  - port: 32222
    protocol: TCP
    targetPort: 80
    NodePort: 32222
  selector:
    app: geocentric-model
  type: NodePort
